# Generated by Django 3.2.7 on 2021-10-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='user',
            new_name='username',
        ),
    ]
