# Generated by Django 3.2.7 on 2021-11-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0002_rename_user_favourites_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourites',
            options={'verbose_name_plural': 'Favourites'},
        ),
    ]
