# Generated by Django 3.2.7 on 2021-09-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_release',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pre_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2,
                                      max_digits=6, null=True),
        ),
    ]
