# Generated by Django 3.2.7 on 2021-10-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_release',
            field=models.BooleanField(default=False),
        ),
    ]
