# Generated by Django 3.2.7 on 2021-10-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211019_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sizes',
        ),
    ]
