# Generated by Django 3.2.7 on 2021-11-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20211106_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=254, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.CharField(max_length=254, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature1',
            field=models.CharField(blank=True, max_length=254,
                                   verbose_name='Feature 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature2',
            field=models.CharField(blank=True, max_length=254,
                                   verbose_name='Feature 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature3',
            field=models.CharField(blank=True, max_length=254,
                                   verbose_name='Feature 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature4',
            field=models.CharField(blank=True, max_length=254,
                                   verbose_name='Feature 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False,
                                      null=True, verbose_name='Has Sizes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='',
                                    verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True,
                                  verbose_name='Image url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=254,
                                   verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pre_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2,
                                      max_digits=6, null=True,
                                      verbose_name='Pre sale price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6,
                                      verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2,
                                      max_digits=6, null=True,
                                      verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(max_length=250, verbose_name='Review Text'),
        ),
    ]
