# Generated by Django 3.2.7 on 2021-11-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20211115_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_release',
        ),
    ]
